DROP TABLE WISH;
DROP TABLE WISH_HISTORY;
DROP TABLE WISH_STACK;
DROP SEQUENCE WISH_HISTORY_SEQ;

CREATE TABLE WISH
(
	NAME VARCHAR2(20) NOT NULL PRIMARY KEY,
	IMAGE VARCHAR2(100) NOT NULL,
	GRADE NUMBER(1) NOT NULL,
	PICKUP NUMBER(1)
);

CREATE TABLE WISH_HISTORY
(
	NUM NUMBER(5) NOT NULL PRIMARY KEY,
	NAME VARCHAR2(20) NOT NULL,
	CATEGORY VARCHAR2(20),
	MDATE DATE
);

CREATE TABLE WISH_STACK
(
	CATEGORY VARCHAR2(20) NOT NULL,
	CS VARCHAR2(10) NOT NULL,
	STACK NUMBER(2) NOT NULL
);

CREATE SEQUENCE WISH_HISTORY_SEQ INCREMENT BY 1 START WITH 1;

INSERT INTO WISH VALUES ('벤티', '벤티.png', 5, 1);
INSERT INTO WISH VALUES ('호두', '호두.png', 5, 0);
INSERT INTO WISH VALUES ('각청', '각청.png', 5, 0);
INSERT INTO WISH VALUES ('모나', '모나.png', 5, 0);
INSERT INTO WISH VALUES ('치치', '치치.png', 5, 0);
INSERT INTO WISH VALUES ('다이루크', '다이루크.png', 5, 0);
INSERT INTO WISH VALUES ('진', '진.png', 5, 0);
INSERT INTO WISH VALUES ('설탕', '설탕.png', 4, 1);
INSERT INTO WISH VALUES ('레이저', '레이저.png', 4, 1);
INSERT INTO WISH VALUES ('노엘', '노엘.png', 4, 1);
INSERT INTO WISH VALUES ('디오나', '디오나.png', 4, 0);
INSERT INTO WISH VALUES ('행추', '행추.png', 4, 0);
INSERT INTO WISH VALUES ('바바라', '바바라.png', 4, 0);
INSERT INTO WISH VALUES ('신염', '신염.png', 4, 0);
INSERT INTO WISH VALUES ('중운', '중운.png', 4, 0);
INSERT INTO WISH VALUES ('베넷', '베넷.png', 4, 0);
INSERT INTO WISH VALUES ('피슬', '피슬.png', 4, 0);
INSERT INTO WISH VALUES ('응광', '응광.png', 4, 0);
INSERT INTO WISH VALUES ('북두', '북두.png', 4, 0);
INSERT INTO WISH VALUES ('향릉', '향릉.png', 4, 0);
INSERT INTO WISH VALUES ('엠버', '엠버.png', 4, 0);
INSERT INTO WISH VALUES ('케이아', '케이아.png', 4, 0);
INSERT INTO WISH VALUES ('리사', '리사.png', 4, 0);

INSERT INTO WISH_STACK VALUES ('픽업', 'STACK', 0);
INSERT INTO WISH_STACK VALUES ('상시', 'STACK', 0);
INSERT INTO WISH_STACK VALUES ('픽업', 'PICKUP', 0);

COMMIT;
